# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET 7 + Tests + Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    env:
      PATH_UNIT_TEST_PROJECT: ./MultiPurposeProjectTest/MultiPurposeProjectUnitTest.csproj
      PATH_INTEGRATION_TEST_PROJECT: ./MultiPurposeProjectIntegrationTest/MultiPurposeProjectIntegrationTest.csproj
      PATH_APP_PROJECT: ./MultiPurposeProject
      DOCKER_CONTAINER_REGISTRY: maiconghidolin
      IMAGE_NAME: $DOCKER_CONTAINER_REGISTRY/multi-purpose-project

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    
    - name: Execute unit tests 
      run: dotnet test ${{ env.PATH_UNIT_TEST_PROJECT }} --verbosity minimal
    
    #- name: Execute integration tests 
    #  run: dotnet test ${{ env.PATH_INTEGRATION_TEST_PROJECT }} --verbosity minimal
      
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKER_CONTAINER_REGISTRY_USERNAME }}
        password: ${{ secrets.DOCKER_CONTAINER_REGISTRY_PASSWORD }}
        
    - name: Build and push image 
      run: |
        cd ${{ env.PATH_APP_PROJECT }}
        docker build . --file Dockerfile --tag ${{ env.IMAGE_NAME }}:latest
        docker tag ${{ env.IMAGE_NAME }}:latest ${{ env.IMAGE_NAME }}:$GITHUB_RUN_NUMBER
        docker push ${{ env.IMAGE_NAME }}
       
    
