# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET 7 + Tests + Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    env:
      PATH_TEST_PROJECT: ./MultiPurposeProjectTest/MultiPurposeProjectUnitTest.csproj
      PATH_APP_PROJECT: ./MultiPurposeProject

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    
    - name: Execute tests 
      run: dotnet test ${{ env.PATH_TEST_PROJECT }} --verbosity minimal
      
